# Generated by Django 5.1.2 on 2024-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(default='School', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='school_pictures/'),
        ),
    ]
