# Generated by Django 5.1.2 on 2024-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_type_alter_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='Company', max_length=20),
        ),
    ]
